Output demo_1.gif

  Set Padding 16
  Set FontFamily "Geist Mono"
  Set TypingSpeed 150ms
  Set FontSize 16
  Set Width 1000
  Set Height 580

  Sleep 333ms
  Type "dssh"
  Sleep 500ms
  Enter

  Sleep 1s
  Type "sky"
  Sleep 1s
  Backspace 3

  Sleep 500ms
  Down 13
  Sleep 1s
  Enter

  Sleep 1250ms
  Set TypingSpeed 50ms
  Type "echo WOW DSSH IS SO COOL I WISH I HAD THIS SOONER"
  Enter
  Sleep 1s
  Set TypingSpeed 150ms
  Type "exit"
  Enter
  Sleep 2s
