Output demo_wizard.gif

  Set Padding 16
  Set FontFamily "Geist Mono"
  Set TypingSpeed 100ms
  Set FontSize 16
  Set Width 1000
  Set Height 580

  Sleep 333ms
  Type "dssh create"
  Sleep 333ms
  Enter

  Sleep 500ms
  Type "rpg-server"
  Down
  Type "npc"
  Down
  Type "192.168.188.7"
  Down
  Type "22222"
  Down
  Type "/var/larp"
  Down
  Sleep 500ms
  Down
  Sleep 500ms
  Down
  Sleep 500ms
  Down
  Sleep 500ms
  Enter
  Sleep 1s
  Right
  Sleep 1s
  Type "rpg"

  Sleep 2s
